# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/nx651j_eea/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/nx651j_eea

PRODUCT_COPY_FILES += \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/sec_s3nrn81_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_firmware.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/sec_s3nrn81_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_rfreg.bin
