# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/nx651j_eea/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/nx651j_eea

PRODUCT_COPY_FILES += \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw22xxx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_fw.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_a8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_a8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_b8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_b8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_c8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_c8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_d8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_d8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_e8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_e8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f0.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f1.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f2.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f3.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f4.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f5.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f6.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f7.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/aw_cfg_f8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw_cfg_f8.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/sec_s3nrn81_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_firmware.bin \
    vendor/nubia/nx651j_eea/proprietary/vendor/firmware/sec_s3nrn81_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn81_rfreg.bin
